# Generated by Django 6.0.7 on 2026-07-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Görev Tipi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Görev Tipi',
                'verbose_name_plural': 'Görev Tipleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(blank=True, choices=[('tyt', 'TYT'), ('ayt', 'AYT')], max_length=3, verbose_name='Sınav Türü')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Sınav Adı')),
                ('exam_date', models.DateField(verbose_name='Tarih')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Sınav Sonucu',
                'verbose_name_plural': 'Sınav Sonuçları',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('category', models.CharField(choices=[('tyt', 'TYT'), ('ayt', 'AYT'), ('okul', 'Okul Dersi')], max_length=4, verbose_name='Kategori')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç (Görüşme Günü)')),
                ('schedule_type', models.CharField(choices=[('timed', 'Saatli'), ('untimed', 'Saatsiz')], default='timed', max_length=8, verbose_name='Program Tipi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='accounts.counselor', verbose_name='Oluşturan Rehber')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Haftalık Program',
                'verbose_name_plural': 'Haftalık Programlar',
                'ordering': ['-start_date'],
                'unique_together': {('student', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(verbose_name='Gün')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dk)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Rehberim.subject', verbose_name='Ders')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Rehberim.tasktype', verbose_name='Metod')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Rehberim.weeklyprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['date', 'start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.FloatField(default=0, verbose_name='Net')),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_nets', to='Rehberim.examresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nets', to='Rehberim.subject')),
            ],
            options={
                'verbose_name': 'Ders Neti',
                'verbose_name_plural': 'Ders Netleri',
                'unique_together': {('exam_result', 'subject')},
            },
        ),
    ]
