# Generated by Django 6.0.7 on 2026-07-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0002_seed_subjects_and_tasktypes'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.counselor', verbose_name='Rehber')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.student', verbose_name='İlgili Öğrenci')),
            ],
            options={
                'verbose_name': 'Takvim Etkinliği',
                'verbose_name_plural': 'Takvim Etkinlikleri',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Hedef')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarihi')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Ulaşıldı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='accounts.counselor', verbose_name='Oluşturan Rehber')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Hedef',
                'verbose_name_plural': 'Hedefler',
                'ordering': ['is_achieved', 'order', 'target_date', '-created_at'],
            },
        ),
    ]
