# Generated by Django 6.0.7 on 2026-07-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0003_calendarevent_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='counselor',
        ),
        migrations.AddField(
            model_name='goal',
            name='exam_scope',
            field=models.CharField(blank=True, choices=[('tyt', 'TYT'), ('ayt', 'AYT')], max_length=3, verbose_name='Sınav Türü'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('deneme_net', 'Deneme Neti'), ('konu', 'Konu Bitirme'), ('kitap_bitirme', 'Kitap Bitirme'), ('kitap_okuma', 'Kitap Okuma')], default='deneme_net', max_length=13, verbose_name='Hedef Türü'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='Rehberim.subject', verbose_name='Ders'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_net',
            field=models.FloatField(blank=True, null=True, verbose_name='Hedef Net'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Hedef'),
        ),
    ]
