# Generated by Django 6.0.7 on 2026-07-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0004_remove_goal_counselor_goal_exam_scope_goal_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['is_achieved', 'target_date', '-created_at'], 'verbose_name': 'Hedef', 'verbose_name_plural': 'Hedefler'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name'], 'verbose_name': 'Görev Tipi', 'verbose_name_plural': 'Görev Tipleri'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='order',
        ),
    ]
