# Generated by Django 6.0.7 on 2026-08-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0005_alter_goal_options_alter_subject_options_and_more'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ders', 'Ders Kitabı'), ('okuma', 'Okuma Kitabı')], default='ders', max_length=5, verbose_name='Kitap Türü')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Kitap Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('baslanmadi', 'Başlanmadı'), ('devam', 'Devam Ediliyor'), ('tamamlandi', 'Tamamlandı')], default='baslanmadi', max_length=10, verbose_name='Durum')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Yayınevi')),
                ('book_format', models.CharField(blank=True, choices=[('paragraf', 'Paragraf'), ('konu_anlatimi', 'Konu Anlatımı'), ('soru_bankasi', 'Soru Bankası'), ('deneme', 'Deneme')], max_length=13, verbose_name='Format')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Yazar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.student', verbose_name='Öğrenci')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='Rehberim.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['status', 'kind', '-created_at'],
            },
        ),
    ]
