# Generated by Django 6.0.7 on 2026-08-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0006_book'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('9', '9. Sınıf'), ('10', '10. Sınıf'), ('11', '11. Sınıf'), ('12', '12. Sınıf')], max_length=2, verbose_name='Sınıf')),
                ('name', models.CharField(max_length=200, verbose_name='Konu')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Rehberim.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['subject', 'grade', 'order', 'name'],
                'unique_together': {('subject', 'grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('baslanmadi', 'Başlanmadı'), ('devam', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='baslanmadi', max_length=10, verbose_name='Durum')),
                ('tests_solved', models.PositiveIntegerField(default=0, verbose_name='Çözülen Test Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='accounts.student', verbose_name='Öğrenci')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Rehberim.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Konu İlerlemesi',
                'verbose_name_plural': 'Konu İlerlemeleri',
                'ordering': ['topic', '-updated_at'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
