# Generated by Django 6.0.7 on 2026-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0008_seed_topics_grade10_math'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Yayınevi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Yayınevi',
                'verbose_name_plural': 'Yayınevleri',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='curriculum',
            field=models.CharField(choices=[('eski', 'Mevcut Müfredat'), ('maarif', 'Maarif Modeli')], default='maarif', max_length=6, verbose_name='Müfredat'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Konu'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'grade', 'curriculum', 'name')},
        ),
    ]
