# Generated by Django 6.0.7 on 2026-08-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0011_seed_publishers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('baslanmadi', 'Başlanmadı'), ('devam', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='baslanmadi', max_length=10, verbose_name='Durum')),
                ('tests_solved', models.PositiveIntegerField(default=0, verbose_name='Çözülen Test Sayısı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_topics', to='Rehberim.book', verbose_name='Kitap')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_links', to='Rehberim.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Kitap Konusu',
                'verbose_name_plural': 'Kitap Konuları',
                'ordering': ['book', 'order'],
                'unique_together': {('book', 'topic')},
            },
        ),
    ]
