# Generated by Django 6.0.7 on 2026-08-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0013_seed_topics_tyt_ayt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Rehberim.book', verbose_name='Kaynak Kitap'),
        ),
    ]
