# Generated by Django 6.0.7 on 2026-08-08 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0014_task_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Seviye'),
        ),
    ]
