# Generated by Django 6.0.7 on 2026-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0015_topicprogress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Soru Sayısı (maks. net)'),
        ),
    ]
