# Generated by Django 6.0.7 on 2026-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0017_seed_question_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectnet',
            name='correct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Doğru'),
        ),
        migrations.AddField(
            model_name='subjectnet',
            name='wrong',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Yanlış'),
        ),
    ]
