# Generated by Django 6.0.7 on 2026-08-09 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0018_subjectnet_correct_subjectnet_wrong'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('schedule_type', models.CharField(choices=[('timed', 'Saatli'), ('untimed', 'Saatsiz')], default='timed', max_length=8, verbose_name='Program Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_templates', to='accounts.counselor', verbose_name='Rehber')),
            ],
            options={
                'verbose_name': 'Program Şablonu',
                'verbose_name_plural': 'Program Şablonları',
                'ordering': ['name'],
                'unique_together': {('counselor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Gün (0-6)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dk)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='Rehberim.book', verbose_name='Kaynak Kitap')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='Rehberim.subject', verbose_name='Ders')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='Rehberim.tasktype', verbose_name='Metod')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Rehberim.programtemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Şablon Görevi',
                'verbose_name_plural': 'Şablon Görevleri',
                'ordering': ['weekday', 'start_time', 'order'],
            },
        ),
    ]
