# Generated by Django 6.0.7 on 2026-08-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0019_programtemplate_templatetask'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtemplate',
            name='auto_apply',
            field=models.BooleanField(default=False, verbose_name='Yeni haftaya otomatik uygula'),
        ),
        migrations.AddField(
            model_name='programtemplate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='accounts.student', verbose_name='Öğrenci (rutin ise)'),
        ),
        migrations.AddConstraint(
            model_name='programtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('auto_apply', False), ('student__isnull', False), _connector='OR'), name='otomatik_rutin_ogrenci_ister'),
        ),
        migrations.AddConstraint(
            model_name='programtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('auto_apply', True)), fields=('student',), name='ogrenci_basina_tek_otomatik_rutin'),
        ),
    ]
