# Generated by Django 6.0.7 on 2026-08-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0020_programtemplate_auto_apply_programtemplate_student_and_more'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='programtemplate',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_templates', to='accounts.counselor', verbose_name='Rehber'),
        ),
        migrations.AddConstraint(
            model_name='programtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('counselor__isnull', False), ('student__isnull', False), _connector='OR'), name='sablonun_sahibi_olmali'),
        ),
        migrations.AddConstraint(
            model_name='programtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('counselor', 'name'), name='genel_sablon_adi_rehberde_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='programtemplate',
            constraint=models.UniqueConstraint(fields=('student', 'name'), name='rutin_adi_ogrencide_benzersiz'),
        ),
    ]
