# Generated by Django 6.0.7 on 2026-08-22 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0021_alter_programtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyprogram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='exam_scope',
            field=models.CharField(blank=True, choices=[('tyt', 'Genel TYT'), ('ayt', 'Genel AYT')], default='', max_length=3, verbose_name='Deneme Kapsamı'),
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('study', 'Çalışma'), ('external', 'Dış Meşguliyet'), ('exam', 'Deneme')], default='study', max_length=8, verbose_name='Blok Türü'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='exam_scope',
            field=models.CharField(blank=True, choices=[('tyt', 'Genel TYT'), ('ayt', 'Genel AYT')], default='', max_length=3, verbose_name='Deneme Kapsamı'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='kind',
            field=models.CharField(choices=[('study', 'Çalışma'), ('external', 'Dış Meşguliyet'), ('exam', 'Deneme')], default='study', max_length=8, verbose_name='Blok Türü'),
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='day_count',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Gün Sayısı'),
        ),
    ]
