# Generated by Django 6.0.7 on 2026-08-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0022_alter_weeklyprogram_unique_together_task_exam_scope_and_more'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDurationDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=100, verbose_name='Konu')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Süre (dk)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_duration_defaults', to='accounts.counselor', verbose_name='Rehber')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_duration_defaults', to='Rehberim.subject', verbose_name='Ders')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_duration_defaults', to='Rehberim.tasktype', verbose_name='Metod')),
            ],
            options={
                'verbose_name': 'Blok Süre Hafızası',
                'verbose_name_plural': 'Blok Süre Hafızası',
                'ordering': ['subject', 'task_type', 'topic'],
                'unique_together': {('counselor', 'subject', 'task_type', 'topic')},
            },
        ),
    ]
