# Generated by Django 6.0.7 on 2026-08-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0023_blockdurationdefault'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogram',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Zamanı'),
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programs', to='accounts.counselor', verbose_name='Onaylayan Rehber'),
        ),
    ]
