# Generated by Django 6.0.7 on 2026-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0024_weeklyprogram_approved_at_weeklyprogram_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='source',
            field=models.CharField(choices=[('personal', 'Kişisel'), ('institutional', 'Kurumsal')], default='personal', max_length=13, verbose_name='Deneme Türü'),
        ),
    ]
