# Generated by Django 6.0.7 on 2026-08-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rehberim', '0025_examresult_source'),
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ad')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('metric', models.CharField(choices=[('exam_net', 'Deneme Neti'), ('topic_completion', 'Konu Tamamlama (%)'), ('compliance', 'Program Uyumu (%)')], max_length=16, verbose_name='Ölçüt')),
                ('scope', models.CharField(blank=True, choices=[('tyt', 'TYT'), ('ayt', 'AYT')], default='', max_length=3, verbose_name='Kapsam')),
                ('threshold', models.FloatField(verbose_name='Eşik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etkin')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.counselor', verbose_name='Rehber')),
            ],
            options={
                'verbose_name': 'Başarım',
                'verbose_name_plural': 'Başarımlar',
                'ordering': ['order', 'metric', 'threshold'],
                'unique_together': {('counselor', 'name')},
            },
        ),
    ]
