# Generated by Django 6.0.7 on 2026-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Davet Kodu'),
        ),
        migrations.AddField(
            model_name='student',
            name='connect_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Bağlanma Kodu'),
        ),
    ]
