# Generated by Django 6.0.7 on 2026-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_counselor_invite_code_student_connect_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='invite_code',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True, verbose_name='Davet Kodu'),
        ),
    ]
